import {
    attribute,
    autoGeneratedHashKey,
    rangeKey,
    table,
} from '@aws/dynamodb-data-mapper-annotations';

@table('cats')
export class Cat {
    
    @autoGeneratedHashKey()
    id: string;

    @attribute()
    name: string;

    @attribute({defaultProvider: () => new Date()})
    createdWhen: Date;
}
